### ISSUE TITLE
[TV Show] Ratings

### ISSUE THREAD

**Issue by KarellenX** [romanvm/kodi.tvmaze#1]
Hello romanvm

I have scraped a tv show today and note the rating is not correct. The following is the rating when exported to nfo file.

`<rating name="default" max="10" default="true">`
`     <value>8.000000</value>`
`     <votes>0</votes>`
`</rating>`

**rating name="default"** = Should detail which provider supplied the rating- IMDB, TV Maze, other
Possible abbreviate the name to **maze** ie. `<rating name="maze"`
**votes**= No votes are scraped

I guess the rating is from TV Maze, but I could not see any ratings for the tv show. Maybe you need to be logged in?

Would you consider cross-scraping IMDB for their ratings also? The IMDB ID is already provided as a unique id.

Thanks :)

**Comment by romanvm** [comment]
Here's the list of supported rating sources: https://romanvm.github.io/Kodistubs/_autosummary/xbmcgui.html#xbmcgui.ListItem.setRating
Yes, the rating is supplied by TV Maze API, I'm not familiar with their site. As for cross-scraping, I'll consider this.

**Comment by KarellenX** [comment]
I was not aware of "supported" ratings and ID's. What is meant to support them? eg, I use "home" as a rating or unique id for my home movies... Kodi still works :)

What would not work if you added another type, even though it is not listed as "supported"? 

Can votes be scraped?

**Comment by romanvm** [comment]
This is what the documentation says: https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__listitem.html#gad1fa7da3c659e70f53abc32ff3526f8e
I don't know how it is implemented internally but I can look.

TV Maze API does not provide the number of votes, only a rating value.

**Comment by KarellenX** [comment]
I only ask out of curiosity as I had no idea that there is some type of restriction in place, whether that be a coding restriction or simply a documentation mention.

But I do note that "default" is not listed in the document but you used it. So I am inclined to wonder if you could just as easily used "maze" to distinguish the scraping site. I also know that media managers use "unknown" which is also not listed in the document.

But apart from that, I have scraped 3 shows in the last couple of days and these were the only issues I came across, but I now understand why the issues exist.

The only other issue, which is beyond your control is the artwork. I have noted the artwork on the site is not very good. There seems to be no quality control for artwork at the site. This will be a problem for many users.

This is an example of a poster that was scraped for a new release tv show...
https://static.tvmaze.com/uploads/images/medium_portrait/213/534571.jpg

I also scraped banner and received landscape image instead as well as fanart with logos (which should be classified as landscape).

Would you be interested in creating a python scraper for TheMovieDB-TV Shows or a new Movie scraper for TVDB's new site?

Thanks :-)

**Comment by romanvm** [comment]
As far as I can see, rating and unique IDs are stored in separate tables in the database, so other types should be supported as well. But I need to look into the Kodi code as well.

Yes, images are a known issue, I have told TV Maze guys about that several times, and they promised me that they were working on that.

As for other scrapers, everything will depend on how much free time I have. Another issue that I'd like to address is per-path settings for Python scrapers, but for that I will need some help from our core devs (and some free time, of course).

**Comment by KarellenX** [comment]
Sorry, but one last comment regarding Ratings in case it helps in any way which I remembered as I was heading off to bed last night.

The Universal Movie Scraper also scrapes Rotten Tomatoes ratings and Metacritic ratings which uses the following values. Some media managers are also using this for ratings and skins have no problems displaying the ratings and logos of the provider. I use them also...

`<rating name="metacritic" max="10">`
  `          <value>6.1</value>`
 `           <votes>6</votes>`
`</rating>`
	`	<rating name="metauser" max="10">`
		`	<value>5.3</value>`
			`<votes>16</votes>`
`		</rating>`
	`	<rating name="tomatometerallcritics" max="10">`
		`	<value>7.9</value>`
			`<votes>24</votes>`
`		</rating>`
	`	<rating name="tomatometerallaudience" max="10">`
		`	<value>7.4</value>`
			`<votes>149</votes>`
`		</rating>`

I think the docs are out of date with what the rest of the community is using.

Thanks.

**Comment by romanvm** [comment]
I'm closing this because currently the scrapers stores all ratings TVMaze provides.

**Comment by KarellenX** [comment]
>I'm closing this because currently the scrapers stores all ratings TVMaze provides.

Yes it will, but skinners will never be able to do this...

![tvmazerating](https://user-images.githubusercontent.com/44626605/69570474-0192a700-1014-11ea-9feb-08d10a142285.jpg)

(and yes I know that is a movie, but it was the screenshot that I had handy)

**Comment by romanvm** [comment]
I'm not quite sure what you mean. TVmaze rating is now stored in the database as `tvmaze`, I specifically checked that. If it is not available via other Kodi APIs (e.g. infolabels), this is not a scraper issue.
![image](https://user-images.githubusercontent.com/1595560/69721263-26bf0c80-111d-11ea-8aed-e0fc010fd09b.png)

**Comment by KarellenX** [comment]
Ok, I misunderstood. Your last comment was closing the thread, but no mention you had updated the rating type.

Thanks
