### ISSUE TITLE
PVR EPG compatible?

### ISSUE THREAD

**Issue by bam80** [romanvm/kodi.tvmaze#13]
Is any possibility to fill PVR's EPG data with this addon?
Were there any attempts/discussion from Kodi side for this, if needed?

**Comment by romanvm** [comment]
I don't use PVR so have no idea what you are asking about. The addon is a metadata provider for medialibrary and certainly does not work with PVR.

**Comment by KarellenX** [comment]
Answered by ksooo... https://forum.kodi.tv/showthread.php?tid=349447

**Comment by bam80** [comment]
@romanvm to make it clear -  PVR channels happen to stream the same movies/TV shows you have in your library. So the idea to fill EPG with the same metadata as scrapers can get looks attractive..
The appropriate PVR skins already exist, e.g https://github.com/louisbraun/skin.unfussy

**Comment by romanvm** [comment]
I'm closing it because I still don't understand the context and think it is not relevant to this metadata scraper.
