### ISSUE TITLE
Accented character in network causes error

### ISSUE THREAD

**Issue by tvgazza911** [romanvm/kodi.tvmaze#16]
Errors such as:

Error Contents: 'ascii' codec can't encode character u'\xc9' in position 2: ordinal not in range(128)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

  File "main.py", line 28, in <module>
                                                router(sys.argv[2][1:])
                                              File "libs\actions.py", line 193, in router
                                                find_show(params['title'], params.get('year'))
                                              File "libs\actions.py", line 53, in find_show
                                                list_item = data_utils.add_main_show_info(list_item, search_result['show'], False)
                                              File "libs\data_utils.py", line 195, in add_main_show_info
                                                video['studio'] = '{0} ({1})'.format(show_info['network']['name'], country['code'])

For example, 'Reeling in the Years' has the network 'RTÉ ONE' with an accented 'e'.

I believe this changeset, removing the u''caused it.

https://github.com/romanvm/kodi.tvmaze/commit/ce697a9e2f40288e7f430e2cbd3dede7ba2106f0#diff-fd9d7d452aaec716d6cf7e31f269ef67R191

I think that you meant to import , unicode_literals in this file, but I'm not entirely certain.

**Comment by romanvm** [comment]
Yes, looks like I forgot to add `unicode_literals` import to data_utils.py

**Comment by romanvm** [comment]
BTW, next time please upload a full Kodi log, preferably in debug mode.
