### ISSUE TITLE
[Episode] UniqueID

### ISSUE THREAD

**Issue by KarellenX** [romanvm/kodi.tvmaze#2]
The uniqueID for episodes is the following when exported to nfo file...

`<uniqueid type="unknown" default="true"></uniqueid>`

1. Should replace the **unknown** entry with **maze**
2. No id is actually scraped. The value is empty which, as you know, can cause issues.

Log file for both reports... https://paste.kodi.tv/odizasopan.kodi

Thanks.

**Comment by romanvm** [comment]
Here's the list of supported unique IDs: https://romanvm.github.io/Kodistubs/_autosummary/xbmcgui.html#xbmcgui.ListItem.setUniqueIDs
I guess they correspond the the columns in the Kodi database. TV maze does not provide external IDs for episodes and they are not used by Python scrapers API.

**Comment by KarellenX** [comment]
It sounds like you are saying that nothing can be done. What are the consequences of files not having a uniqueID?

**Comment by romanvm** [comment]
Yes, there is nothing can be done if TV Maze does not provide them. As I said, episode Unique IDs are not used by Python scraper API, so the only consequence I can think of is for some external tools that work with database data via JSON API, like TractTV scrobbler. But I don't know how they really work. My scrobbler for next-episode.net does not require per-episode unique IDs.
