### ISSUE TITLE
`addon_data\metadata.tvmaze` has `cache` folder inside

### ISSUE THREAD

**Issue by stdedos** [romanvm/kodi.tvmaze#20]
**Issue description:**

Taking a backup with https://kodi.wiki/view/Add-on:Backup, leads to adding cache data inside it (instead of just getting settings etc.)

**Kodi debug log:**

**Additional context**

**Comment by romanvm** [comment]
`addon_data` directory is a legit place for storing addon-specific data like caches, local databases and such. I don't see what can be done about this.

**Comment by stdedos** [comment]
I am not an add-on specialist. I would like that my backup contains restore-essential data (settings, required add-on dbs, etc), and avoid non-essential data (such as caches).

If you claim there is nothing that can be done, then I guess that's it.

Thank you for your time 😃

**Comment by KarellenX** [comment]
@pkscout had this discussion with @karlson2k (an older team member). Discussion starts here... https://forum.kodi.tv/showthread.php?tid=357232&pid=2989217#pid2989217

pkscout ended up changing the location of the cache in his tv show scraper.

**Comment by stdedos** [comment]
Yeah, I guess the proposed solution is here https://forum.kodi.tv/showthread.php?tid=357232&pid=2989515#pid2989515:
> ```
> os.path.join('special://temp/scrapers', ADDON.getAddonInfo('id'))
> ```
with notes here https://forum.kodi.tv/showthread.php?tid=357232&pid=2990046#pid2990046:
> Kodi doesn't perform clean-up inside special://temp/, but Kodi cleans old files inside special://temp/scrapers/metadata.tvshows.themoviedb.org.python/ according to the scraper setting in addon.xml. I suggest to drop "/cache" from the end of the path as second level directories are not checked.

and the discussion "ends" here https://forum.kodi.tv/showthread.php?tid=357232&pid=2989915#pid2989915

**Comment by pkscout** [comment]
The thing to remember is that this alternate location for cache files is really only useful for scrapers. As @romanvm said, addon_data is a valid location for just about anything related to an addon, so if you want to do a backup that doesn't include certain things, you might have to do an exclusion list of some sort (like folders named 'cache').  I only changed the location for the next version of the TMDb TV Show scraper because (a) it made the behavior consistent with the non-python scraper and (b) the TMDb TV Show python scraper is now the default for Kodi 19, and I **really** wanted the behavior to stay similar to the old scraper.

**Comment by stdedos** [comment]
I just read this: https://github.com/robweber/xbmcbackup/wiki/Advanced-Editor, and I thought I could've applied your suggestion immediately; after all, I am *always* up-to-date ... **ehnt**

![image](https://user-images.githubusercontent.com/133706/101080363-641c6c80-35b1-11eb-9332-8bd7bb186f9d.png)

So, tl;dr: not gonna die (a couple of 10s MB after all), but "I thought it'd be better to go there".
It seems I have to live with it for a long time anyway (or start adding "Unknown Sources")

**Comment by robweber** [comment]
Will just add (saw this tagged in a Backup addon issue) that the [Advanced Editor](https://github.com/robweber/xbmcbackup/wiki/Advanced-Editor) functionality of the Backup addon does allow for directory exclusions. Currently only available in the Matrix repo but you can manually download a Krypton/Leia compatible version from the repo page.
