### ISSUE TITLE
Unable to update show (error occured)

### ISSUE THREAD

**Issue by dirkronsmans** [romanvm/kodi.tvmaze#22]
**Issue description:**
I'm trying to update the info for "The Falcon and Winter Soldier (2021), the interface show my selection of the show and then I get "an error occured, check logs"

**Kodi debug log:**
https://paste.kodi.tv/pujepakice.kodi

**Additional context**
worked fine before.. suddenly happens. Using Matrix

**Comment by romanvm** [comment]
The updated version with fixed caching has been submitted to the Kodi repo. Please wait until it is reviewed and published.
