### ISSUE TITLE
[TV Show] UniqueID

### ISSUE THREAD

**Issue by KarellenX** [romanvm/kodi.tvmaze#3]
I note there is no UniqueID from TV Maze. Is this intentional or an oversight? The following is what is scraped...

`    <uniqueid type="imdb">tt7826108</uniqueid>`
`    <uniqueid type="tvdb" default="true">335985</uniqueid>`

Just wondering what would happen if neither IMDB or TVDB fields were completed at TV Maze.

**Comment by romanvm** [comment]
Here's the list of supported unique ids: https://romanvm.github.io/Kodistubs/_autosummary/xbmcgui.html#xbmcgui.ListItem.setUniqueIDs
TV Maze is not among them. If a tvdb or imdb unique ID is missing, then no artwork will be added (Python scrapers use unique ids to download images for a specific show).

**Comment by tvjan** [comment]
It might be a naive question from my part: But what can be done to be considered for addition?

**Comment by romanvm** [comment]
@tvjan  My post above is not correct, there is no limitation for unique IDs. We actually discussed this with KarellenX outside GitHub and the issue was resolved long ago (https://github.com/romanvm/kodi.tvmaze/blob/master/metadata.tvmaze/libs/data_utils.py#L94) and should have been closed.
