### ISSUE TITLE
The scraper fails to parse a show that has an .nfo file with episodeguide section

### ISSUE THREAD

**Issue by romanvm** [romanvm/kodi.tvmaze#4]
If a show has an .nfo file in its directory with `episodeguide` section, e.g:
```xml
<episodeguide>
    <url>http://www.thetvdb.com/api/1D62F2F90030C444/series/350665/all/en.zip</url>
</episodeguide>
```
this URL is passed to getepisodelist call instead of the one set by the scraper and the scraper fails to get the list of episodes. This looks like a Kodi bug.

Possible workaround: if a non-numeric ID is passed to getepisode list call, parse it the same way as in nfourl call to obtain TVmaze show ID.

**Comment by KarellenX** [comment]
That is the TVDB `<episodeguide>`  for the v1 API. Kodi no longer recognises v1 and requires v2 `<episodeguide>` URL

I don't even think that v1 is still in use at TVDB. I recall talk of it being disabled when v3 was released.

See here... https://forum.kodi.tv/showthread.php?tid=323588
