### ISSUE TITLE
Scraping shows with no rating

### ISSUE THREAD

**Issue by tvgazza911** [romanvm/kodi.tvmaze#5]
Whenever a show does not have enough votes to have a rating, it will appear in the API as:
`"rating":{"average":null}`

This causes issue with the set_rating function as it tries to parse _null_ as a float.

*** Unhandled exception detected: <type 'exceptions.TypeError'> float() argument must be a string or a number ***

https://github.com/romanvm/kodi.tvmaze/blob/7228caec6ab3089f42133994ac05e15ef2f0f579/metadata.tvmaze/libs/data_utils.py#L108

It should have a check similar to the one above the line `if show_info['rating'] is not None:` but instead ensuring that show_info['rating']['average'] isn't _null_.

**Comment by romanvm** [comment]
Fixed in #8
