### ISSUE TITLE
Episode not being scraped

### ISSUE THREAD

**Issue by SweetthD3ViL** [romanvm/kodi.tvmaze#7]
Hello there, 

Being a TVMaze user to keep track of m shows, I changed all my kodis to used your addon today. All went well (expect that it re-scrapped all my database, resetting all episodes watch status..)

Anyway, all were pick up apart from the second episode of Mrs. Flecther. (https://www.tvmaze.com/shows/35786/mrs-fletcher) Not sure why?

**Comment by KarellenX** [comment]
The title of that episode is **Free Sample**

The word **Sample** is a trigger word in Kodi which forces Kodi to ignore the file.

Remove the word **Sample** out of the filename and try again.

**Comment by SweetthD3ViL** [comment]
Jesus! Thank you, you learn every day! 
Simple when you know.... 
You are a star, thank you for the prompt reply - all sorted.

**Comment by romanvm** [comment]
Closing as solved.
