### ISSUE TITLE
Studio list grouping incorrectly

### ISSUE THREAD

**Issue by tvgazza911** [romanvm/kodi.tvmaze#9]
The Studio list (which are Networks & Web Channels on TVmaze) is grouping two 'studios' of the same name even if they have a different ID or Country.

Take these or example:

https://www.tvmaze.com/networks/3/abc
https://www.tvmaze.com/networks/245/abc

If you added a show from each network, the studio list shows them both under 'ABC' even though they belong to different networks.

**Comment by romanvm** [comment]
Kodi stores a studio name as a single string, so I'm not sure how to handle this situation.

**Comment by tvgazza911** [comment]
I think that the best thing here would be include the country code in parenthesis, i.e. ABC (US) & ABC (JP).

I've just noticed from the code that the studio isn't added at all for web channels.

I'll put in a pull request for these changes.
